### ISSUE TITLE
Starting repl from file on windows does not work ( all path separator are removed from the path)

### ISSUE THREAD

**Issue by Cedric-Venet** [zjhmale/vscode-idris#100]
Even after #90 (I use v0.9.0 and had the same issue with the previous version), start or refresh repl still remove all path separator from the path. Example:
:l d:MyBackupsandboxidristestDec.idr
(real path been D:\MyBackup\sandbox\idris\test\Dec.idr)

**Comment by be5invis** [comment]
@Cedric-Venet OS version? plugin version? is `ipkg` being used?

**Comment by Cedric-Venet** [comment]
Windows 10, extension v0.9.0 (is this the plugin you speak of?), not ipkg (I opened a folder in vscode but its just a few independant files)

**Comment by be5invis** [comment]
@Cedric-Venet If you know some JS, you can try do this:

open `C:\Users\`_your name_`\.vscode\extensions\zjhmale.idris-0.9.0\out\idris\commands.js`, navigate to this block:

```js
let startup = (uri) => {
  const pathToIdris = vscode.workspace.getConfiguration('idris').get('executablePath');
  const idrisPath = which.sync(pathToIdris)
  const pkgOpts = ipkg.getPkgOpts(innerCompilerOptions)
  term = vscode.window.createTerminal("Idris REPL", idrisPath, pkgOpts)

  if (innerCompilerOptions.src && uri.includes(innerCompilerOptions.src)) {
    term.sendText(`:cd ${path.resolve(innerCompilerOptions.src)}`)
    term.sendText(`:l ${path.relative(path.resolve(innerCompilerOptions.src), path.resolve(uri))}`)
    term.show()
  } else {
    term.sendText(`:l ${uri}`)
    term.show()
  }
}
```
change it into this:
```js
let startup = (uri) => {
console.log(uri) // ← ADD THIS LINE
  const pathToIdris = vscode.workspace.getConfiguration('idris').get('executablePath');
  const idrisPath = which.sync(pathToIdris)
  const pkgOpts = ipkg.getPkgOpts(innerCompilerOptions)
  term = vscode.window.createTerminal("Idris REPL", idrisPath, pkgOpts)

  if (innerCompilerOptions.src && uri.includes(innerCompilerOptions.src)) {
    term.sendText(`:cd ${path.resolve(innerCompilerOptions.src)}`)
    term.sendText(`:l ${path.relative(path.resolve(innerCompilerOptions.src), path.resolve(uri))}`)
    term.show()
  } else {
    term.sendText(`:l ${uri}`)
    term.show()
  }
}```

Then restart VSCode, type `Toggle developer tool` in the command panel, and then fire the `Start REPL` command. See what the F12 developer tool shows.

**Comment by Cedric-Venet** [comment]
I added those three lines:
  console.log(uri)
  console.log(`:l ${uri}`)
  console.log(innerCompilerOptions.src)

And I get:
[Extension Host] d:\MyBackup\sandbox\idris\test\Dec.idr
[Extension Host] :l d:\MyBackup\sandbox\idris\test\Dec.idr
[Extension Host] undefined

looks like its term.sendText which misbehave. I added .replace(/\\/g, "/") before sending the text and it works now (note that using .replace(/\\/g, "\\\\") did not work, which seems really strange to me):
term.sendText(`:l ${uri}`.replace(/\\/g, "/"))

Thanks for the help, I can try to do a PR tonight if you want.

**Comment by zjhmale** [comment]
@be5invis Thanks for the help!

@Cedric-Venet Path separator missing in load path on windows is reported twice before #83 #65 and we are still facing this issue, sorry for that.

One thing is really wired that REPL can work perfectly with my windows10 virtual machine, I don't know if this issue is related to Visual Studio or MSBuild or some other concrete .Net frameworks.

![screenshot](https://cloud.githubusercontent.com/assets/6234553/25367667/bf6b038e-29a9-11e7-9b44-46eacf582d30.gif)

And yes, the solution you got here looks good and can also work as expected both on OSX and Windows10 from my side, the reason why `replace(/\/g, "\\")` did not work is that `\` need to be escaped.

Looking forward to your PR :)

**Comment by Cedric-Venet** [comment]
@zjhmale markdown ate my '\\' I tried `.replace(/\\/g, "\\\\") ` and it did not work its why I was surprised. It seems that on (both) of my computers '\\' really don't go through.

**Comment by zjhmale** [comment]
@Cedric-Venet OK, but `term.sendText(`:l ${uri}`.replace(/\\/g, "/"))` is completely doable for this, just feel free to open a pull request for this :)
