### ISSUE TITLE
Is it really necessary to pop up the output panel when typechecking a file?

### ISSUE THREAD

**Issue by be5invis** [zjhmale/vscode-idris#109]

**Comment by zjhmale** [comment]
@be5invis Yes, I also considered switching to a new way to display the type checking result, one possible way is to show `problem` panel when the type checking process failed, but it is still pending https://github.com/Microsoft/vscode/issues/22885 I think, and another way is to show the result on status bar which is already implemented https://github.com/zjhmale/vscode-idris/issues/106, but I haven't released this feature yet since I got some problem with vsce.

**Comment by zjhmale** [comment]
What do you have in mind is the best way to show the type checking result?

**Comment by chantisnake** [comment]
I would give a +1 to the problem panel

**Comment by zjhmale** [comment]
@chantisnake problem panel is supposed to be the best solution here indeed, but we still have to wait it appears in the next release of VSCode.

**Comment by be5invis** [comment]
maybe a :+1: :-1: icon like this?
https://marketplace.visualstudio.com/items?itemName=roscaj.dafny-vscode

**Comment by chantisnake** [comment]
I think @be5invis idea is generally valid for now. Idris atom uses a method like this (a notification in the command bar)

**Comment by zjhmale** [comment]
@be5invis @chantisnake OK, thanks for the reference, I will remove the stupid output channel and use the thumb icons.

**Comment by zjhmale** [comment]
So it is also no need to display the type checking errors in output channel right? cause we can check all the warnings and errors in problem panel.

**Comment by chantisnake** [comment]
I think so.

**Comment by ndmitchell** [comment]
I found the forced switch to output to be exceptionally annoying since I was quickly doing other stuff in another terminal window. I would definitely like this to be eliminated.

**Comment by zjhmale** [comment]
@ndmitchell I will address issue ASAP :)

**Comment by zjhmale** [comment]
- [ ] Add option to turn off stupid output channel.
- [ ] Using thumb icons.
- [ ] Add a preview HTML page to display errors.

**Comment by ndmitchell** [comment]
Note that the thing that broke my flow was forced switching to the output channel - actually having the output channel wasn't problematic.

**Comment by be5invis** [comment]
@zjhmale @ndmitchell Add an option for that, "showOutputWhenTypechecking"

**Comment by zjhmale** [comment]
@be5invis Thanks, adding an option is on the todo list already.

**Comment by zjhmale** [comment]
Hi @ndmitchell @be5invis @chantisnake Sorry for the huge delay, I was busy with something else these days, the `showOutputWhenTypechecking` option is already added and default to false, the new release will be tonight or tomorrow, Cheers!

**Comment by pandemonium** [comment]
When showOutputWhenTypechecking is false, saving the file or activating the idris.typecheck command does not actually type-check the file. This is a bug but since there is a discussion about it here I thought I'd mention it.

**Comment by zjhmale** [comment]
@pandemonium Thanks, I will address this bug, there is also a bug of Github so I just see the notification of this comment right now with a huge delay.

**Comment by swr1bm86** [comment]
@pandemonium Thanks, I will address it. There is also a bug of Github that I just got the notification of your comment with a huge delay.
