### ISSUE TITLE
Shortcut confliction

### ISSUE THREAD

**Issue by zjhmale** [zjhmale/vscode-idris#15]
Since other sophisticated extensions are all released without carrying any default key bindings, so I'm just seriously considering about removing all the default key bindings for actions. Any ideas about this @be5invis

**Comment by be5invis** [comment]
@zjhmale You know there is a key binding filter called `editorLangId`

**Comment by be5invis** [comment]
`"when": "editorFocus && editorLangId == idris",` ← add into package.json

**Comment by zjhmale** [comment]
@be5invis Thanks! I added [this restriction](https://github.com/zjhmale/vscode-idris/blob/master/src/controller.js#L26) explicitly, but it does not work as expected 😅

**Comment by zjhmale** [comment]
Just removed all these TAB space here 😄

![image](https://cloud.githubusercontent.com/assets/6234553/23896253/aabea4d6-08e3-11e7-82e4-def1b09f7347.png)

`v0.3.1` will be released tonight, thanks, @be5invis.

Cheers!
