### ISSUE TITLE
Highlighting Type class and Data constructor

### ISSUE THREAD

**Issue by zjhmale** [zjhmale/vscode-idris#24]
Currently, the type classes and data constructors are not highlighted.

![image](https://cloud.githubusercontent.com/assets/6234553/24203789/a80d6726-0f51-11e7-8a67-71f5f4aafcba.png)

And this is highlighting with the syntax file translated directly from the atom package.

![image](https://cloud.githubusercontent.com/assets/6234553/24203738/81634b54-0f51-11e7-9268-ef517312da46.png)

Maybe we can go back to the old highlighting style? @be5invis

**Comment by be5invis** [comment]
@zjhmale I am fixing that.

**Comment by zjhmale** [comment]
Thanks! @be5invis

**Comment by zjhmale** [comment]
Hi @be5invis I just pulled you fix but type classes and data constructors are still not highlighted. Am I missing something here? Thx in advance.

![image](https://cloud.githubusercontent.com/assets/6234553/24204792/7e86e866-0f54-11e7-816e-b02c2c39e01b.png)

**Comment by be5invis** [comment]
Do you have a proper theme? Data constructors are in `entity.name.constructor.idris`.

**Comment by be5invis** [comment]
In Railgun theme:

![image](https://cloud.githubusercontent.com/assets/240091/24206208/82237f76-0f58-11e7-81a0-03b49ccf32fd.png)

**Comment by be5invis** [comment]
OK i switched into `entity.name.function.idris` for data constructors.

**Comment by zjhmale** [comment]
@be5invis Thanks! It works now. I work with OneDark theme 😅
