### ISSUE TITLE
Remove annoying warning for hover

### ISSUE THREAD

**Issue by zjhmale** [zjhmale/vscode-idris#28]
https://github.com/zjhmale/vscode-idris/blob/master/src/idris/commands.js#L41

**Comment by philipcraig** [comment]
This message is indeed quite annoying. How can I install a pre-release, if the release is going to be a few days?

**Comment by zjhmale** [comment]
@philipcraig, sorry for that, I will release it now 😅

**Comment by zjhmale** [comment]
Hi @philipcraig, `v0.3.7` is already released.

**Comment by philipcraig** [comment]
Thanks for the release! However, all I now get on all hovers is a message saying "didn't load path/to/source.idr" where the path is my path. Even hello world does this.

**Comment by zjhmale** [comment]
@philipcraig That is because the Idris file itself can not be type checked, maybe I should show the error message directly instead of showing this confusing message.

**Comment by philipcraig** [comment]
Good idea to show Idris's messages directly. If I'd been able to see Idris' message, which was about incompatible versions and advised cleaning the .ibc files, I'd have known what to do.

**Comment by zjhmale** [comment]
Yes, we need to create an issue here, maybe you can do me the favor 😄

**Comment by philipcraig** [comment]
will do
