### ISSUE TITLE
Prettify symbols

### ISSUE THREAD

**Issue by zjhmale** [zjhmale/vscode-idris#29]
Note for contribution to https://github.com/siegebell/vsc-prettify-symbols-mode.

**Comment by philipcraig** [comment]
We may not need this. Developers can have this by installing Hasklig font, then turning on ligatures in the editor. Certainly, it looks great for me already

**Comment by philipcraig** [comment]
Also on this point, the Haskell extension here https://github.com/hoovercj/vscode-ghc-mod somehow honours the ``Editor.fontLigatures`` setting when it shows the types on hover, but this one doesn't. It would be great if this extension honoured the setting

**Comment by zjhmale** [comment]
@philipcraig Thx! I'm also thinking about not to use the prettify symbol because it may introduce some unpredictable behavior. I also use Hasklig myself 😄

**Comment by zjhmale** [comment]
Cool, I will figure out how to support fontLigatures on hover, thx for reporting 😄

**Comment by zjhmale** [comment]
Close via https://github.com/siegebell/vsc-prettify-symbols-mode/pull/26
