### ISSUE TITLE
REPL

### ISSUE THREAD

**Issue by zjhmale** [zjhmale/vscode-idris#3]
pending on upstream issue

`https://github.com/Microsoft/vscode/issues/547`

**Comment by PhilAndrew** [comment]
Can REPL be added soon?

**Comment by zjhmale** [comment]
I think the upstream issue is still pending, but using terminal API seems to be a good approach, I'll try that these days 😄

**Comment by zjhmale** [comment]
[Integrated Terminal](https://code.visualstudio.com/docs/editor/integrated-terminal) is for the rescue.
