### ISSUE TITLE
hover-type text should use ligatures and Hasklig font if they are set up

### ISSUE THREAD

**Issue by philipcraig** [zjhmale/vscode-idris#33]
The editor windows look great with the Hasklig font set up and ``editor.fontLigatures`` turned on.

One difference to the Haskell ghc-mod vscode extension is that the hover type messages in the Haskell one respect the ligature setting and show hover ligatures, but the Idris one currently doesn't.

**Comment by zjhmale** [comment]
Duplicate with #29, I do have an idea to fix this. Will be supported in the next release.

**Comment by zjhmale** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6234553/24331964/de60259e-1270-11e7-91e4-ddb179a89ed5.gif)

**Comment by be5invis** [comment]
@zjhmale Is that my code?

**Comment by zjhmale** [comment]
@be5invis Yeah, I just started to explore your code 😄

**Comment by philipcraig** [comment]
Looks great, thanks! When is the next release?

**Comment by zjhmale** [comment]
@philipcraig The next release will be out of box within two days, maybe tonight, you won't wait too long 😄

**Comment by zjhmale** [comment]
@philipcraig @be5invis  `v0.3.9` is already released, Cheers 😄
