### ISSUE TITLE
right-click shortcuts on some Idris commands

### ISSUE THREAD

**Issue by philipcraig** [zjhmale/vscode-idris#34]
Enhancement request:

To make the plugin even more amazing, it would be great if the appropriate Idris commands were exposed via right-clicking in an identifier rather than only through the control-shift-p menu.

**Comment by zjhmale** [comment]
Yes indeed, I will do some investigation on that.

**Comment by philipcraig** [comment]
I'm sure happy with this commit. However the commands I'd **really** like on right-click are the Idris-specific ones that are awesome and supported by the idris server (and that we have ctrl-shift bindings for), like:

C-c C-s: Create an initial pattern match clause for a type declaration
C-c C-m: Add missing pattern-match cases to an existing definition
C-c C-a: Attempt to solve a hole automatically.
C-c C-e: Extract a hole or provisional definition name to an explicit top level definition
C-c C-c: Case split the pattern variable under point, or fill the hole at point with a case expression.
C-c C-w: Add a with block for the pattern-match clause under point

Should I open another issue or could this one get reopened?
