### ISSUE TITLE
The regexp for identifiers leaves one or more single quotation marks out of the identifier

### ISSUE THREAD

**Issue by philipcraig** [zjhmale/vscode-idris#35]
Thus for hover-type, if a method is called, e.g. ``count'``, rather than ``count``, then the incorrect identifier is passed to idris-server for type identification, and the hovertext shows a "No such variable" message

**Comment by zjhmale** [comment]
This may relate to an upstream issue, need some hack here.

**Comment by zjhmale** [comment]
Also support `'count` now.
