### ISSUE TITLE
Have option to show :doc and fallback to :type

### ISSUE THREAD

**Issue by philipcraig** [zjhmale/vscode-idris#37]
Another feature request copied from https://github.com/hoovercj/vscode-ghc-mod

It has a preference:   ``haskell.ghcMod.onHover``, which can be set to ``fallback`` mode where it does ``:info``, then falls back to ``type`` if ``:info`` returns nothing.

My request is to have a ``fallback`` mode for vscode-idris, that shows the ``:doc`` output on type-hover.

That way the user sees the richest possible information on type hover.

**Comment by zjhmale** [comment]
Thanks, I also notice this feature this afternoon, it will be supported in the next release!

**Comment by zjhmale** [comment]
This is the last issue need to be addressed before the new release, also need some documentation adding up for the consistency.

**Comment by zjhmale** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6234553/24369640/3937fa14-1357-11e7-8ffd-bb841ed0dbcc.gif)
