### ISSUE TITLE
add a readme saying how to contribute

### ISSUE THREAD

**Issue by philipcraig** [zjhmale/vscode-idris#46]
I've a couple of times wanted to send a pull request, but:

1) I can't trivially see how to build and test the extension for myself. Add a document explaining this, plus any other requirements that must be met for a potential pull request to be considered
2) (related) I suspect there might be some deployment/configuration files that aren't part of the repo. If so, could they be added?

The point is to lower the barrier to sending potentially useful pull requests

**Comment by zjhmale** [comment]
Hi @philipcraig, honestly, VSCode extension development workflow is much more clear than other editors than I ever worked with (Atom, LightTable, IntelliJ IDEA, VIM), yes, I will add a `Contribution` section on readme, and before that, you can walk this [document](https://code.visualstudio.com/docs/extensions/overview) first, it can help you to build some intuition about the whole picture. And for the second point, I have to say everything you need is inside this repo now. I will fix this issue ASAP, looking forward to your PRs 😄
