### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by smobs** [zjhmale/vscode-idris#52]
I'm running idris 0.99.1 on OSX

Extension is awesome, but after using it for 45 minutes or so running commands (exercises in TDDII) slows down dramatically and there is an idris process using most of my system's RAM.  

Workaround: Closing and opening VS Code every now and again.

**Comment by zjhmale** [comment]
Hi @smobs, thanks for reporting, I will do some investigation here.

**Comment by zjhmale** [comment]
Yeah, the memory usage of `idris` process just keep growing, I will fix it in the next release.

![image](https://cloud.githubusercontent.com/assets/6234553/24486013/5dcd1c3a-153a-11e7-901b-9cf97f9a591c.png)

**Comment by zjhmale** [comment]
@smobs I think Idris 0.99.2 has resolved this issue, you can kindly upgrade to that version, and I will remove all those unmaintainable hacks.

**Comment by zjhmale** [comment]
Currently, no matter how many commands you send to Idris process, the memory usage will keep as low as around 300MB.

![image](https://cloud.githubusercontent.com/assets/6234553/24578908/c3c1f396-171d-11e7-93e7-033afa43cafc.png)

**Comment by zjhmale** [comment]
Oh, we will still meet this issue, so annoying.

**Comment by smobs** [comment]
I've upgraded to 1.0 🎉

**Comment by zjhmale** [comment]
@smobs Great, but I think this issue is still standing there so I revert the commit 😅
