### ISSUE TITLE
Commands don't work the first time on unsaved files

### ISSUE THREAD

**Issue by smobs** [zjhmale/vscode-idris#55]
If the file is unsaved then the first time that you issue a command the file is saved, but the command is not run (`Send to Repl` and `Eval` commands aren't affected, but `Show Type` and `Lift hole` are)

**Comment by smobs** [comment]
On 6.0.1

**Comment by smobs** [comment]
PS thanks for fixing the other issue so quickly and all your hard work

**Comment by zjhmale** [comment]
Hi @smobs, actually I can not reproduce your issue here, like the screenshot below, when I issue a command (`Send to REPL` and `Eval`) on an unsaved file, everything works as expected 😅 

![screenshot](https://cloud.githubusercontent.com/assets/6234553/24558753/dfe7528c-166e-11e7-89be-6bdd68a112da.gif)

Can you kindly offer more details about your issue, a screenshot will be really helpful for me to locate the issue 😄

**Comment by smobs** [comment]
Not near a computer at the moment, but I worded the report badly. Send to
repl and eval are ok, it's the other commands that are showing this
behaviour.

**Comment by zjhmale** [comment]
OK, wait for your more detailed report, I just tried some commands and can not get into the scenario you described 😅

**Comment by smobs** [comment]
Initial State:
![image](https://cloud.githubusercontent.com/assets/3480534/24560461/ce1a72c0-163a-11e7-82d0-687deeeec1c9.png)

Case Split on xs `Cmd + Alt + Shift + c`

![image](https://cloud.githubusercontent.com/assets/3480534/24560512/fcadd38e-163a-11e7-8276-f68122a04e54.png)

Note how the file is now saved.

Case Split on xs `Cmd + Alt + Shift + c`
 
![image](https://cloud.githubusercontent.com/assets/3480534/24560558/286e7820-163b-11e7-8853-3db91567d70c.png)

Expected behaviour: No need for the second command.

**Comment by smobs** [comment]
My guess would be that it was caused by the fix to #52, something to do with the model in [https://github.com/zjhmale/vscode-idris/blob/master/src/idris/commands.js] not getting reintialised  after it is destroyed.

**Comment by smobs** [comment]
I think I've traced the cause:

1) Firing a command initializes the model.
2) As part of the command [getWord](https://github.com/zjhmale/vscode-idris/blob/9bdfbd11acfe90d31bbd7e7cc32c90bf277210c7/src/idris/commands.js#L55) is called
3) This saves the file as part of [getCurrentPosition](https://github.com/zjhmale/vscode-idris/blob/9bdfbd11acfe90d31bbd7e7cc32c90bf277210c7/src/idris/commands.js#L33)
4) Typecheck on save triggers the typecheck command, which calls `destroy` when it finishes.
5) Now that the model is null the command is unable to complete.

**Comment by zjhmale** [comment]
Hi @smobs Thanks for the detailed description! I do have an idea to fix this, thanks again 😄

**Comment by zjhmale** [comment]
This will also fix #59 by the same design, we need to mock a reader monad here 😅
