### ISSUE TITLE
Windows 10: Typechecking in editor gives "Can't find import" but works with language-idris plugin for Atom

### ISSUE THREAD

**Issue by jchoules** [zjhmale/vscode-idris#66]
I have an Idris source file which imports another file in the same directory as follows:

`one.idr`:

    module One

    foo : Nat
    foo = Z

`two.idr`:

    module Two

    import one

If I try to typecheck `two.idr` from within Atom, using the [language-idris](https://atom.io/packages/language-idris) plugin, then it works fine. But when I try the same thing in VSCode, I get the following error:

    Errors (1)
    (no file):0:0
    Can't find import one

This is using Idris 1.0, VSCode 1.10.2, plugin version 0.6.6.

**Comment by zjhmale** [comment]
Thanks for reporting, this will be fixed in the next release.
