### ISSUE TITLE
Publish on the Extension Marketplace

### ISSUE THREAD

**Issue by brendanzab** [zjhmale/vscode-idris#7]
This looks like a great extension! When do you think it will be ready for publishing on the marketplace?

**Comment by zjhmale** [comment]
Hi @brendanzab it is so great to see you around here. :smiley: I was busy with exams these months and forgot to pubish it. :sweat_smile: I will release it ASAP, you won't wait too long!

**Comment by brendanzab** [comment]
No worries, take your time! Just thought it would be good to have an issue up for the benefit of others!

**Comment by be5invis** [comment]
Any progress?

**Comment by zjhmale** [comment]
Hi @brendanzab @be5invis, [v0.3.0](https://github.com/zjhmale/vscode-idris/releases/tag/v0.3.0) has been released and also published on the [marketplace](https://marketplace.visualstudio.com/items?itemName=zjhmale.Idris), Thanks for reminding me to release it and Happy New Year 🎉
