### ISSUE TITLE
Commands not working in latest version (on Windows)

### ISSUE THREAD

**Issue by Porges** [zjhmale/vscode-idris#83]
In the latest version some commands don't seem to work. Starting the Idris REPL works, but the other ones like "show holes" or "split case" do not.

I don't see any errors printed anywhere, so I'm not sure where to start debugging.

I'm using Windows, Idris extension is 0.8.9, VS Code 1.11.2

**Comment by CarstenKoenig** [comment]
I just noticed that as well and I think the problem is that the `\` in windows paths are not based on (for example a path `c:\temp\test.idr` is given as `:l c:temptest.idr` to the repl

**Comment by Porges** [comment]
I'm actually beginning to suspect there was something strange in the last Windows update. It wasn't working on either of my machines, but I got another update last night and everything seems to be working again.

**Comment by zjhmale** [comment]
Yes, it should be the issue with windows path separator, I will fix this ASAP :)

**Comment by zjhmale** [comment]
Hi @Porges @CarstenKoenig, I installed a latest windows 10 virtual machine, and everything works fine for me, do you guys still got this issue?

![screenshot](https://cloud.githubusercontent.com/assets/6234553/25302783/edaee7c0-2778-11e7-8d01-1e6ff205bece.gif)

**Comment by Porges** [comment]
No, with the latest build it is working again. I'll close the issue.
Thanks 🙂
